#+ summary: Search by protein name
#+ description: Search for proteins containing the supplied string in their name. The default value searches for the string 'Protein'.
#+ endpoint: https://swel.macs.hw.ac.uk/data/repositories/idpkg
#+ pagination: 100
#+ defaults:
#+   - search: "Protein"
#+ tags:
#+   - Protein

PREFIX schema: <https://schema.org/>

SELECT DISTINCT ?s ?name
WHERE {
    GRAPH ?g {
        ?s a schema:Protein ;
          schema:name ?name
        FILTER REGEX(?name, ?_search, "i")
    }
}
